var config = {
  emojis: {
      'TV':       '📺' ,
      'Bed':      '🛏'  ,
      'Rice':     '🍚' ,
      'Toilet':   '🚽' ,
      'Earth':    '🌍' ,
      'Up':       '🔼' ,
      'Down':     '🔽' ,
  },
  rows: 9,
  cols: 12,
  cells: [
    { w:1, h:1,
      y:0, x:2,
      icon: 'TV',
      onPress: {action: 'ChangeRoom', args: ['Living']},
    },
    { w:1, h:1,
      y:0, x:3,
      icon: 'Bed',
      onPress: {action: 'ChangeRoom', args: ['Bedroom']},
    },
    { w:1, h:1,
      y:0, x:4,
      icon: 'Rice',
      onPress: {action: 'ChangeRoom', args: ['Kitchen']},
    },
    { w:1, h:1,
      y:0, x:5,
      icon: 'Toilet',
      onPress: {action: 'ChangeRoom', args: ['Bathroom']},
    },

    { w:1, h:1,
      y:0, x:7,
      icon: 'Earth',
      onPress: {action: 'ChangeRoom', args: ['All']},
    },


    { w:1, h:1,
      y:4, x:1,
      icon: 'Up',
      onPress: {action: 'Music.VolumeUp', args: ['All']},
    },
    { w:1, h:1,
      y:5, x:1,
      icon: 'Down',
      onPress: {action: 'Music.VolumeDown', args: ['All']},
    },
  ]
};