var config = {
  emojis: {
      'TV':       '📺' ,
      'Bed':      '🛏'  ,
      'Rice':     '🍚' ,
      'Toilet':   '🚽' ,
      'Earth':    '🌍' ,
      'Up':       '🔼' ,
      'Down':     '🔽' ,
      'Notes':    '🎶',
  },
  rows: 9,
  cols: 12,
  cells: [
    { w:1, h:1,
      y:0, x:2,
      icon: 'TV',
      onPress: {action: 'ChangeRoom', args: ['Living']},
    },
    { w:1, h:1,
      y:0, x:3,
      icon: 'Bed',
      onPress: {action: 'ChangeRoom', args: ['Bedroom']},
    },
    { w:1, h:1,
      y:0, x:4,
      icon: 'Rice',
      onPress: {action: 'ChangeRoom', args: ['Kitchen']},
    },
    { w:1, h:1,
      y:0, x:5,
      icon: 'Toilet',
      onPress: {action: 'ChangeRoom', args: ['Bathroom']},
    },

    { w:1, h:1,
      y:0, x:7,
      icon: 'Earth',
      onPress: {action: 'ChangeRoom', args: ['All']},
    },

    { w:1, h:1,
      y:7, x:0,
      icon: 'Notes',
      onPress: {action: 'Music.GetState', args: []},
    },
    { w:10, h:1,
      y:7, x:1,
      claz: 'state-Music',
      onPress: {action: 'Music.GetState', args: []},
    },
    { y:7, x:2, w:0 },
    { y:7, x:3, w:0 },
    { y:7, x:4, w:0 },
    { y:7, x:5, w:0 },
    { y:7, x:6, w:0 },
    { y:7, x:7, w:0 },
    { y:7, x:8, w:0 },
    { y:7, x:9, w:0 },
    { y:7, x:10, w:0 },
    
    { w:1, h:1,
      y:7, x:11,
      icon: 'Notes',
      onPress: {action: 'Music.GetState', args: []},
    },


    { w:1, h:1,
      y:4, x:1,
      icon: 'Up',
      onPress: {action: 'Music.VolumeUp', args: ['All']},
    },
    { w:1, h:1,
      y:5, x:1,
      icon: 'Down',
      onPress: {action: 'Music.VolumeDown', args: ['All']},
    },
  ]
};