[Unit]
Requires=srv-usenet-downloads-incomplete.mount usenet-sab-remote.service
BindsTo=srv-usenet-downloads-incomplete.mount
After=srv-usenet-downloads-incomplete.mount usenet-sab-remote.service

[Service]
ExecStartPre=/usr/bin/mountpoint -q /srv/usenet/downloads/complete/remote
ExecStart=
ExecStart=/usr/bin/docker compose up -d --force-recreate --wait --wait-timeout 180
