- action:
  - scene: scene.scene_bedroom_off
  alias: bedroom_switch_bedside_on_down_double
  condition: []
  id: bedroom_switch_bedside_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_bedroom_high
  alias: bedroom_switch_bedside_on_up_double
  condition: []
  id: bedroom_switch_bedside_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_bathroom_closet_off
  alias: bedroom_switch_closet_on_down_double
  condition: []
  id: bedroom_switch_closet_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.bedroom_switch_closet
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_bathroom_closet_medium
  alias: bedroom_switch_closet_on_up_double
  condition: []
  id: bedroom_switch_closet_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.bedroom_switch_closet
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_kitchen_living_off
  alias: entry_switch_kitchen_on_down_double
  condition: []
  id: entry_switch_kitchen_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.entry_switch_kitchen
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_kitchen_living_high
  alias: entry_switch_kitchen_on_up_double
  condition: []
  id: entry_switch_kitchen_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.entry_switch_kitchen
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_all_off
  alias: global_switch_hall_on_down_double
  condition: []
  id: global_switch_hall_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.global_switch_hall
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_all_high
  alias: global_switch_hall_on_up_double
  condition: []
  id: global_switch_hall_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.global_switch_hall
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_dining_off
  alias: kitchen_switch_dining_on_down_double
  condition: []
  id: kitchen_switch_dining_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.kitchen_switch_dining
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_dining_high
  alias: kitchen_switch_dining_on_up_double
  condition: []
  id: kitchen_switch_dining_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.kitchen_switch_dining
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - service: rest_command.bedroom_roller_down
  - service: rest_command.bedroom_blackout_up
  - service: rest_command.office_blackout_up
  alias: morning_blinds_up
  id: morning_blinds_up
  trigger:
  - event: sunrise
    offset: +00:00:00
    platform: sun
- action:
  - service: rest_command.bedroom_roller_down
  - service: rest_command.bedroom_blackout_down
  - service: rest_command.living_roller_down
  - service: rest_command.office_roller_down
  - service: rest_command.office_blackout_down
  alias: night_blinds_down
  id: night_blinds_down
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
- action:
  - scene: scene.scene_office_off
  alias: office_switch_main_on_down_double
  condition: []
  id: office_switch_main_on_down_double
  trigger:
  - event_data:
      entity_id: zwave.office_switch_main
      scene_data: 3
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_office_high
  alias: office_switch_main_on_up_double
  condition: []
  id: office_switch_main_on_up_double
  trigger:
  - event_data:
      entity_id: zwave.office_switch_main
      scene_data: 3
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
- action:
  - scene: scene.scene_all_high
  alias: scene_all_high
  condition: []
  description: ''
  id: scene_all_high
  trigger:
  - platform: webhook
    webhook_id: scene_all_high
- action:
  - scene: scene.scene_all_off
  alias: scene_all_off
  condition: []
  description: ''
  id: scene_all_off
  trigger:
  - platform: webhook
    webhook_id: scene_all_off
- action:
  - scene: scene.scene_bathroom_closet_medium
  alias: scene_bathroom_closet_medium
  condition: []
  description: ''
  id: scene_bathroom_closet_medium
  trigger:
  - platform: webhook
    webhook_id: scene_bathroom_closet_medium
- action:
  - scene: scene.scene_bathroom_closet_off
  alias: scene_bathroom_closet_off
  condition: []
  description: ''
  id: scene_bathroom_closet_off
  trigger:
  - platform: webhook
    webhook_id: scene_bathroom_closet_off
- action:
  - scene: scene.scene_bathroom_high
  alias: scene_bathroom_high
  condition: []
  description: ''
  id: scene_bathroom_high
  trigger:
  - platform: webhook
    webhook_id: scene_bathroom_high
- action:
  - scene: scene.scene_bathroom_medium
  alias: scene_bathroom_medium
  condition: []
  description: ''
  id: scene_bathroom_medium
  trigger:
  - platform: webhook
    webhook_id: scene_bathroom_medium
- action:
  - scene: scene.scene_bathroom_off
  alias: scene_bathroom_off
  condition: []
  description: ''
  id: scene_bathroom_off
  trigger:
  - platform: webhook
    webhook_id: scene_bathroom_off
- action:
  - scene: scene.scene_bedroom_high
  alias: scene_bedroom_high
  condition: []
  description: ''
  id: scene_bedroom_high
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_high
- action:
  - scene: scene.scene_bedroom_medium
  alias: scene_bedroom_medium
  condition: []
  description: ''
  id: scene_bedroom_medium
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_medium
- action:
  - scene: scene.scene_bedroom_off
  alias: scene_bedroom_off
  condition: []
  description: ''
  id: scene_bedroom_off
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_off
- action:
  - scene: scene.scene_closet_high
  alias: scene_closet_high
  condition: []
  description: ''
  id: scene_closet_high
  trigger:
  - platform: webhook
    webhook_id: scene_closet_high
- action:
  - scene: scene.scene_closet_medium
  alias: scene_closet_medium
  condition: []
  description: ''
  id: scene_closet_medium
  trigger:
  - platform: webhook
    webhook_id: scene_closet_medium
- action:
  - scene: scene.scene_closet_off
  alias: scene_closet_off
  condition: []
  description: ''
  id: scene_closet_off
  trigger:
  - platform: webhook
    webhook_id: scene_closet_off
- action:
  - scene: scene.scene_kitchen_high
  alias: scene_kitchen_high
  condition: []
  description: ''
  id: scene_kitchen_high
  trigger:
  - platform: webhook
    webhook_id: scene_kitchen_high
- action:
  - scene: scene.scene_kitchen_living_high
  alias: scene_kitchen_living_high
  condition: []
  description: ''
  id: scene_kitchen_living_high
  trigger:
  - platform: webhook
    webhook_id: scene_kitchen_living_high
- action:
  - scene: scene.scene_kitchen_living_off
  alias: scene_kitchen_living_off
  condition: []
  description: ''
  id: scene_kitchen_living_off
  trigger:
  - platform: webhook
    webhook_id: scene_kitchen_living_off
- action:
  - scene: scene.scene_kitchen_medium
  alias: scene_kitchen_medium
  condition: []
  description: ''
  id: scene_kitchen_medium
  trigger:
  - platform: webhook
    webhook_id: scene_kitchen_medium
- action:
  - scene: scene.scene_kitchen_off
  alias: scene_kitchen_off
  condition: []
  description: ''
  id: scene_kitchen_off
  trigger:
  - platform: webhook
    webhook_id: scene_kitchen_off
- action:
  - scene: scene.scene_living_high
  alias: scene_living_high
  condition: []
  description: ''
  id: scene_living_high
  trigger:
  - platform: webhook
    webhook_id: scene_living_high
- action:
  - scene: scene.scene_living_medium
  alias: scene_living_medium
  condition: []
  description: ''
  id: scene_living_medium
  trigger:
  - platform: webhook
    webhook_id: scene_living_medium
- action:
  - scene: scene.scene_living_off
  alias: scene_living_off
  condition: []
  description: ''
  id: scene_living_off
  trigger:
  - platform: webhook
    webhook_id: scene_living_off
- action:
  - scene: scene.scene_office_high
  alias: scene_office_high
  condition: []
  description: ''
  id: scene_office_high
  trigger:
  - platform: webhook
    webhook_id: scene_office_high
- action:
  - scene: scene.scene_office_medium
  alias: scene_office_medium
  condition: []
  description: ''
  id: scene_office_medium
  trigger:
  - platform: webhook
    webhook_id: scene_office_medium
- action:
  - scene: scene.scene_office_off
  alias: scene_office_off
  condition: []
  description: ''
  id: scene_office_off
  trigger:
  - platform: webhook
    webhook_id: scene_office_off
