---

# https://pimylifeup.com/raspberry-pi-print-server/
# Consider: https://www.techradar.com/how-to/computing/how-to-turn-the-raspberry-pi-into-a-wireless-printer-server-1312717

# Don't setup samba because ew windows

- name: install cups
  become_user: root
  become: yes
  apt:
      name: cups
      state: present

- name: add pi user to lpadmin group
  become_user: root
  become: yes
  user:
    name: pi
    group: lpadmin
    append: yes

- name: allow remote access from whole network
  become_user: root
  become: yes
  shell: |
    cupsctl --remote-any
    touch /tmp/cupsctl-remote-any-done
  args:
    creates: /tmp/cupsctl-remote-any-done

- name: restart cups service
  become_user: root
  become: yes
  service:
    name: cups
    state: started
