---
- name: get install script
  get_url:
    url: https://install.pi-hole.net
    dest: ./install-pihole.sh
    mode: '0755'

- name: invoke install script
  become_user: root
  become: yes
  shell: |
    ./install-pihole.sh
    touch /tmp/pihole-installed
  args:
    creates: /tmp/pihole-installed

