---
- name: replace /etc/hosts
  template:
    src: etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0664

- name: replace /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0664

- name: create new inventory file on local machine
  become: False
  local_action:
    module: template
    src: post_init.j2
    dest: "{{ playbook_dir }}/post_init.ini"
