---

# Must be stopped prior to copying config
# since hass writes its state to disk on shutdown.
- name: stop hass5 service
  become_user: root
  become: true
  service:
    name: hass5
    state: stopped
    enabled: yes
  ignore_errors: yes  # The first time we run the service won't exist. Could set vars or something?

- name: copy hass5 systemd unit file
  become_user: root
  become: true
  copy:
    src: hass5.service
    dest: /etc/systemd/system/hass5.service
    owner: root
    group: root
    mode: 0664



- name: Remove .storage dir
  become_user: root
  become: true
  file:
    path: /home/pi/repo/HomeAssistantConfig/.storage
    state: absent

- name: copy HomeAssistantConfig
  synchronize:
      group: no
      checksum: yes
      copy_links: yes
      links: yes
      partial: yes
      perms: no
      recursive: yes
      times: no
      # ↓ must be no because don't want to delete hass's internal dbs/logs/deps
      delete: no
      src: "{{ playbook_dir }}/../HomeAssistantConfig/"
      dest: /home/pi/repo/HomeAssistantConfig/
      rsync_opts:
      - "--exclude=venv"
      - "--exclude=deps"

- name: start home-assistant service
  become_user: root
  become: true
  service:
    name: hass5
    state: started
    enabled: yes
    daemon_reload: true
