---

- name: apply roles
  hosts: pre_init
  roles:
   - {name: networking, become: true, become_user: root}
   - {name: hostname, become: true, become_user: root}

  pre_tasks:
   - name: import vars
     include_vars: main.yml
