---

- name: install dependencies
  become_user: root
  become: true
  apt:
    pkg:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libffi-dev
    - libxmlsec1-dev
    - libffi6
    - liblzma-dev
    # Need python-pip in order to use the `pip` ansible module (in the home-assistant role)
    # even though we use `pip3.8`. Unsure if this wants to live in the home-assistant role
    # or here in the python role (since really we always want pip to be available because
    # welcome to the future that is 2005).
    - python-pip
    state: present
    update_cache: yes  # Run apt-get update first.

- name: upload install file
  copy:
    src: install-pyenv.sh
    dest: /tmp/install-pyenv.sh
    mode: 'a+x'

- name: run install file
  become_user: root
  become: true
  command: /tmp/install-pyenv.sh
  args:
    creates: /usr/local/bin/python3.8

